config/routes.rb
Rails.application.routes.draw do
  
  devise_for :customers
  
  get "tags/:tag" => "profiles#index", as: :tag

  post '/rate' => 'rater#create', :as => 'rate'
  get "/messages" => redirect("/conversations")
  resources :messages do
  member do
    post :new
  end
end
resources :conversations do
  member do
    post :reply
    post :trash
    post :untrash
  end
 collection do
    get :trashbin
    post :empty_trash
 end
end

  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations", :omniauth_callbacks => "callbacks" }
  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end

  get "additional_fields/:id" => "users#additional_fields", as: :additional_fields

  resources :profiles do
    collection do
      get 'search'
    end
    resources :orders 
    resources :reviews
  end

  post '/complete_purchase/:id' => "orders#complete_purchase", as: :complete_purchase
  get 'cindarella/:id' => "orders#cindarella"
  
  get "sales" => "orders#sales"
  get "purchases" => "orders#purchases"

  get 'complete_profile' => "profiles#complete_profile" #show of /profiles/:id
  get 'bank_account/:id' => "profiles#bank_account", as: :bank_account
  post 'update_bank_account/:id' => "profiles#update_bank_account", as: :update_bank_account
  
  get 'pages/about'
  get 'pages/contact'
  get 'home' => "pages/home"
  get 'pages/type'

  root 'pages#home'

end

app/models/profile.rb
class Profile < ActiveRecord::Base



	belongs_to :user
	has_many :orders
	has_many :reviews, dependent: :destroy
  
	acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :industries, :companies


	validates :years_of_experience, :experience_level, :portfolio_link, :tag_list, :industry_list, :company_list, presence: true
	validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
	validates :company, :location, :summary, :image, :title, :linked_link, presence: true, unless: :email_signup?


	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "16x16>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def email_signup?
  	self.user.provider == "linkedin"
  end

  def search_data
  	{
  		title: title,
  		company: company,
  		user_title: user.headline,
  		industry: user.industry,
  		tag_name: tags.map(&:name),
  		first_name: user.first_name,
  		last_name: user.last_name,
  		location: user.location,
  		location1: location,
  	}
  end

  def self.facets_search(params)
    query = params[:query].presence || "*"
    conditions = {}
    conditions[:first_name] = params[:first_name] if params[:first_name].present?

    profiles = Profile.search query, where: conditions, 
      facets: [:first_name], 
      smart_facets: true, page: params[:page], suggest: true, highlight: true,
      per_page: 10
    profiles
  end

  

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy, :bank_account, :update_bank_account]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :bank_account, :update_bank_account]
  before_action :check_user, only: [:edit, :update, :destroy, :bank_account, :update_bank_account]
  

  def bank_account
  end



  def update_bank_account
    @profile.user_id = current_user.id

    Stripe.api_key = ENV["STRIPE_SECRET_KEY"]
    token = params[:stripeToken]

    stripe_account = Stripe::Account.create( 
      :managed => true, 
      :country => 'US', 
      :email => current_user.email,
      :bank_account => token, 
      ) 

    current_user.stripe_account = stripe_account.id
    current_user.save

    respond_to do |format|
      if @profile.save
        format.html { redirect_to sales_path(@profile), notice: 'Bank account information was successfully updated.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def complete_profile
    @user = current_user
  end

  def index
      @q = Profile.ransack(params[:q])
      @profiles = @q.result.includes(:user)
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
      @user = @profile.user.id 
      @reviews = Review.where(:profile_id => @profile.id).order("created_at DESC")
      @average_rating = @reviews.average(:rating)
  end

  # GET /profiles/new
  def new
    if current_user.profile.nil?
      @profile = Profile.new
      @disable_nav = true
    else
      flash[:alert] = "Dude, you can only create one profile."
      redirect_to profile_path(current_user.profile)
    end
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    params[:profile][:tag_list] = params[:profile][:tag_list]
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id

    # Store friendly profile URI
    current_user.profile_uri = getUniqueURI(current_user) 
    current_user.save

    respond_to do |format|
      if @profile.save
        format.html { redirect_to profile_path(@profile), notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      if params[:id].to_i != 0
        @profile = Profile.find(params[:id])
        # @user = User.find(params[:id])
      else
        @user = User.find_by_profile_uri(params[:id])
      end
    end
      

    def check_user
      if current_user != @profile.user
        redirect_to root_url, alert: "Sorry, this does not belong to you"
      end
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:company_list, :industry_list, :tag_list, :image, :years_of_experience, :experience_level, :price, :portfolio_link, :linked_link, :location, :company, :title, :summary)
    end

    def getUniqueURI(user)
      pin = current_user.id
      "#{user.first_name}-#{user.last_name}-#{pin}"
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper

end

app/views/profiles/_new_profile_header.html.erb
<header class="navbar navbar-inverse normal" role="banner">
  		<div class="container">
    		<div class="navbar-header">
		      	<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
		      	</button>
      			<a href="/" class="navbar-brand">OneHourUX</a>
    		</div>
  		</div>
	</header>

app/views/profiles/bank_account.html.erb
<h3>Bank Account Information</h3>
<p>We do NOT store your bank account information. Your information is secured with Stripe</p>

<%= form_tag update_bank_account_path(@profile), method: "post" do %>
  <div id="stripe_error" class="alert alert-danger" style="display:none">
    <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </div>
  
  <div class="row">
    <div class="col-md-1">
      <div class="form-group">
        <%= label_tag :country %>
        <%= text_field_tag :country, nil, { :name => nil, :'data-stripe' => "country", class: "form-control", placeholder: "US" } %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= label_tag :routing_number %>
        <%= text_field_tag :routing_number, nil, { :name => nil, :'data-stripe' => "routingNumber", class: "form-control", placeholder: "Enter routing number" } %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
        <div class="form-group">
          <%= label_tag :account_number %>
          <%= text_field_tag :account_number, nil, { :name => nil, :'data-stripe' => "accountNumber", class: "form-control" } %>
        </div>
    </div>
  </div>

  <div class="form-group">
    <%= submit_tag " Add Bank Account ", class: "button button-small" %>
  </div>

<% end %>
  
  

app/views/profiles/cindarella.html.erb
<div class="row  margin-top-20"> <!-- open main row -->
    <div class="col-xs-12 col-sm-8 col-md-9"> <!-- right side of page -->
        <div class="row">
            <div id="profile-style">
                <div class="col-sm-3">
                    <%= image_tag "default.jpg", size: "150x150", class: "img-responsive img-circle" %>
                </div> <!-- close left side of left side -->
                <div class="col-xs-12 col-sm-9">
                    <h1><%= "#{@profile.user.first_name} #{@profile.user.last_name}" %></h1>
                    <h3><%= @profile.user.headline %></h3>
                    <h5>Portfolio: <%= link_to "www.#{@profile.portfolio_link}", @profile.portfolio_link %></h5>
                    <h5>LinkedIn: <%= link_to "#{@profile.user.linkedin_url}", @profile.user.linkedin_url %></h5>
                    <div class="form-inline">
                        <div class="form-group">
                            <p><span class="label label-default">Marketing<a href=""></a></span></p>
                        </div>
                        <div class="form-group">
                            <p><span class="label label-default">Digital Marketing</span></p>
                        </div>
                        <div class="form-group">
                            <p><span class="label label-default">Consumer Products</span></p>
                        </div>
                        <div class="form-group">
                            <p><span class="label label-default">Healthcare</span></p>
                        </div>
                    </div>          
                </div> <!-- close right side of left side -->
            </div> <!-- close profile-style -->
        </div> <!-- close row --><br>

        <div class="row">
            <div class="col-xs-12">
                <div class="form-group">
                    <h3>Professional Summary</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus mollis orci, sed rhoncus sapien nunc eget odio.</p>
                </div>
            </div>
        </div> <!-- close row --><br>

        <div class="row">
            <div class="col-xs-12 col-sm-11">
                <h3>Experience By Industry:</h3>
                <div class="form-inline">
                    <div class="form-group">
                        <h5><span class="label label-default">Marketing</span></h5>
                    </div>
                    <div class="form-group">
                        <h5><span class="label label-default">Digital Marketing</span></h5>
                    </div>
                    <div class="form-group">
                        <h5><span class="label label-default">Consumer Products</span></h5>
                    </div>
                    <div class="form-group">
                        <h5><span class="label label-default">Healthcare</span></h5>
                    </div>
                    <div class="form-group">
                        <h5><span class="label label-default">Marketing</span></h5>
                    </div>
                    <div class="form-group">
                        <h5><span class="label label-default">Digital Marketing</span></h5>
                    </div>
                    <div class="form-group">
                        <h5><span class="label label-default">Consumer Products</span></h5>
                    </div>
                    <div class="form-group">
                        <h5><span class="label label-default">Healthcare</span></h5>
                    </div>
                    <div class="form-group">
                        <h5><span class="label label-default">Marketing</span></h5>
                    </div>
                    <div class="form-group">
                        <h5><span class="label label-default">Digital Marketing</span></h5>
                    </div>
                    <div class="form-group">
                        <h5><span class="label label-default">Consumer Products</span></h5>
                    </div>
                    <div class="form-group">
                        <h5><span class="label label-default">Healthcare</span></h5>
                    </div>
                </div>                  
            </div>
        </div> <!-- close row --><br>

        <section id="past-companies">
            <div class="row">
                <div class="col-xs-12">
                    <h3>Past Companies:</h3>
                        <div class="form-inline">
                            <div class="form-group">
                                <h5><span class="label label-default">Digital Marketing</span></h5>
                            </div>
                            <div class="form-group">
                                <h5><span class="label label-default">Consumer Products</span></h5>
                            </div>
                            <div class="form-group">
                                <h5><span class="label label-default">Healthcare</span></h5>
                            </div>
                            <div class="form-group">
                                <h5><span class="label label-default">Marketing</span></h5>
                            </div>
                        </div>                  
                </div>
            </div> <!-- close row -->
        </section> <!-- close past-companies --><br>

        <div id="device-experience">
            <div class="row">
                <div class="col-xs-12">
                    <h3>Device Experience:</h3>
                        <div class="form-inline">
                            <div class="form-group">
                                <h5><span class="label label-default">Digital Marketing</span></h5>
                            </div>
                            <div class="form-group">
                                <h5><span class="label label-default">Consumer Products</span></h5>
                            </div>
                            <div class="form-group">
                                <h5><span class="label label-default">Healthcare</span></h5>
                            </div>
                            <div class="form-group">
                                <h5><span class="label label-default">Marketing</span></h5>
                            </div>
                        </div>                  
                </div>
            </div> <!-- close row -->
        </div> <!-- close device-experience --><br>

        
        <div class="row">
            <div class="col-md-12">
                <h3>Reviews & Feedback:</h3>
            </div>
            <div id="profile-style">
                <div class="col-sm-8">
                    <div class="form-inline">
                        <div class="form-group">
                            <h4>Super Awesome Advice</h4>
                        </div>
                        <div class="form-group">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus mollis orci, sed rhoncus sapien nunc eget odio.</p>
                        </div> 
                    </div> <!-- close inline-form            -->
                </div> <!-- close sm-8 -->
                <div class="col-sm-4">
                    <h5>May 2015</h5>
                    <div class="form-inline">
                        <div class="form-group">
                            <h5>4.94/5.00 </h5>
                        </div>
                        <div class="form-group">
                            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        </div>
                        <div class="form-group">
                            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        </div>
                        <div class="form-group">
                            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        </div>
                        <div class="form-group">
                            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        </div>
                        <div class="form-group">
                            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div> <!-- close row -->
    </div> <!-- close right side of page-->


    <div class="col-xs-12 col-sm-4 col-md-3"> <!-- left side of page -->
        <div class="center">
            <%= link_to "Hire Me Now", new_profile_order_path(@profile), class: "button", data: { no_turbolink: true } %>
            <h5>or</h5>
            <%= link_to "Send me a message", new_message_path(:user => @user), class: "btn btn-link" %>
        </div>
            <hr style="height:4px;border:none;color:#555;background-color:#555;" />
            <h5><%= number_to_currency(@profile.price) %></h5>
            <hr style="height:1px;border:none;color:#555;background-color:#555;" />
            <h5><div class="form-inline">
                        <div class="form-group">
                            <h5>4.94/5.00</h5>
                        </div>
                        <div class="form-group">
                            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        </div>
                        <div class="form-group">
                            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        </div>
                        <div class="form-group">
                            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        </div>
                        <div class="form-group">
                            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        </div>
                        <div class="form-group">
                            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        </div>
                    </div></h5>
            <hr style="height:1px;border:none;color:#555;background-color:#555;" />
            <h5>28 Times Hired</h5>
            <hr style="height:1px;border:none;color:#555;background-color:#555;" />
            <h5>English, German, Farsi</h5>
            <hr style="height:1px;border:none;color:#555;background-color:#555;" />
            <h5>Los Angeles, California</h5>
            <hr style="height:1px;border:none;color:#555;background-color:#555;" />
        </div>
    </div> <!-- close left side  -->
</div> <!-- close main row -->

app/views/profiles/index.html.erb
<div class="row">
	<div class="col-md-3">
		<% if @profiles.present? %>
					<div class="caption">
			<h3>Filters</h3>
			<%= search_form_for @q do |f| %>
				<div class="form-group">
					<%=  f.label :price, "Hourly Rate" %>
					<%=  f.text_field :price_gteq, class: "form-control", placeholder: "10" %>
					<p>to</p>
					<%=  f.text_field :price_lteq, class: "form-control", placeholder: "300" %>
				</div>
				<div class="form-group">
					<%=  f.label :title_or_user_headline_cont, "Title" %>
					<%=  f.text_field :title_or_user_headline_cont, class: "form-control" %>
				</div>
				<div class="form-group">
					<%=  f.label :location_cont, "Location" %>
					<%=  f.text_field :location_or_user_location_cont, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.submit "Update", class: "button button-xs" %>
				</div>

				<%= link_to "clear filters", profiles_path, class: "btn btn-link" %>
				
			<% end %>
		</div> <!-- caption -->
		<% end %>

	</div> <!-- col-md-3 -->
	<div class="col-md-9">
		<% @profiles.each do |profile| %>
			<div class="thumbnail">
				<div class="row">
					<div class="col-sm-2">
						<div class="caption center">
							<% if profile.user.linkedin_photo_url.present? %>
	                <%= image_tag(profile.user.linkedin_photo_url, size: "125x125", class: "img-responsive img-circle") %>
	            <% else %>
	                <%= image_tag(profile.image.url, size: "125x125", class: "img-responsive img-circle") %>
	            <% end %>
						</div> <!-- caption -->
					</div> <!-- close sm-3 -->
					<div class="col-sm-7">
						<div class="caption">
							
							<h3 style="margin-top: 0px"><%= "#{profile.user.first_name} #{profile.user.last_name}" %></h3>
							<h4 class="nice-grey">
								<% if profile.user.provider == "linkedin" %>
									<%= "#{profile.user.headline}" %> 
								<% else %>
									<%= "#{profile.title} at #{profile.company}" %>
								<% end %>
								
							</h4>
							<h5 class="nice-grey"><%= profile.user.location %></h5>
							<%= raw profile.tag_list.map { |t| link_to t, tag_path(t), class: "skills" }.join(" ") %>
							<p class="light-grey">
								<% if profile.user.provider == "linkedin" %>
									<%= truncate(profile.user.summary, length: 210) %>
								<% else %>
									<%= truncate(profile.summary, length: 210) %>
								<% end %>
							</p>
						</div> <!-- caption -->
					</div> <!-- close sm-7 -->
					<div class="col-sm-3">
						<div class="caption">
							<%= link_to "View Profile", profile_path(profile), class: "button button-small btn-block" %>
							<br><br>
							<h3><%= number_to_currency(profile.price) %>/hour</h3>
							<hr>
							<p>
								3.50/5.00
							</p>
						</div>
					</div>
				</div> <!-- row -->
			</div> <!-- close thumbnail -->
		<% end %> <!-- close .each loop -->
	</div> <!-- md-9 -->
</div>

app/views/profiles/show.html.erb
<div class="row  margin-top-20"> <!-- open main row -->
    <div class="col-xs-12 col-sm-8 col-md-8"> <!-- right side of page -->
        <div class="row">
            <div class="col-sm-3 col-lg-2">
                <% if @profile.user.linkedin_photo_url.present? %>
                    <%= image_tag(@profile.user.linkedin_photo_url, size: "125x125", class: "img-responsive img-circle") %>
                <% else %>
                    <%= image_tag(@profile.image.url, size: "125x125", class: "img-responsive img-circle") %>
                <% end %>
            </div> <!-- close left side of left side -->
            <div class="col-xs-12 col-sm-9 col-lg-10">
                <div id="profile-style">
                    <h1><%= "#{@profile.user.first_name} #{@profile.user.last_name}" %></h1>
                    <% if @profile.user.provider == "linkedin" %>
                        <h3><%= "#{@profile.user.headline} at #{@profile.company}" %></h3>
                        <h5>LinkedIn: <%= link_to "#{@profile.user.linkedin_url}", @profile.user.linkedin_url, :target => "_blank" %></h5>
                    <% else %>
                        <h3><%= "#{@profile.title} at #{@profile.company}" %></h3>
                        <h5>LinkedIn: <%= link_to "https://www.linkedin.com/#{@profile.linked_link}", "https://#{@profile.linked_link}", :target => "_blank"  %></h5>
                    <% end %>
                    <h5>Portfolio: <%= link_to "#{@profile.portfolio_link}", "http://#{@profile.portfolio_link}", :target => "_blank" %></h5>
                    
                </div>

                <div class="form-inline">
                    <% @profile.tag_list.each do |profile| %>
                        <span class="skills"><%= profile %></span>
                    <% end %>
                </div>          
            </div> <!-- close right side of left side -->
        </div> <!-- close row --><br>

        <div class="row">
            <div class="col-xs-12">
                <div class="form-group">
                    <h3>Professional Summary</h3>
                    <% if @profile.user.provider == "linkedin" %>
                        <p><%= @profile.user.summary %></p>
                    <% else %>
                        <p><%= @profile.summary %></p>
                    <% end %>
                    
                </div>
            </div>
        </div> <!-- close row --><br>

        <div class="row">
            <div class="col-xs-12 col-sm-11">
                <h3>Experience By Industry:</h3>
                <div class="form-inline">
                    <% @profile.industry_list.each do |profile| %>
                        <span class="skills"><%= profile %></span>
                    <% end %>
                </div>          
            </div>
        </div> <!-- close row --><br>

        <section id="past-companies">
            <div class="row">
                <div class="col-xs-12">
                    <h3>Past Companies:</h3>
                        <div class="form-inline">
                            <% @profile.company_list.each do |profile| %>
                                <span class="skills"><%= profile %></span>
                            <% end %>
                        </div>           
                </div>
            </div> <!-- close row -->
        </section> <!-- close past-companies --><br>

        <!-- <div id="device-experience">
            <div class="row">
                <div class="col-xs-12">
                    <h3>Device Experience:</h3>
                        <div class="form-inline">
                            <div class="form-group">
                                <span class="industry">Digital Marketing</span>
                            </div>
                            <div class="form-group">
                                <span class="industry">Consumer Products</span>
                            </div>
                            <div class="form-group">
                                <span class="industry">Healthcare</span>
                            </div>
                            <div class="form-group">
                                <span class="industry">Marketing</span>
                            </div>
                        </div>                  
                </div>
            </div> <!-- close row -->
        <!-- </div>  --><!-- close device-experience --><!-- <br> -->

        <div class="row">
            <div class="col-md-12">
                <h3>Reviews & Feedback:</h3>
            </div>
        </div> <!-- close row -->
        <div class="row">
            <% if @average_rating.present? %>
                <% @reviews.each do |review| %>
                    <div class="col-sm-8">                            
                        <div class="form-group">
                            <h4><%= review.title %></h4>
                        </div>
                        <div class="form-group">
                            <p><%= review.comment %></p>
                        </div> 
                    </div> <!-- close sm-8 -->
                    <div class="col-sm-4">
                        <div class="form-group">
                            <p><%= review.created_at.strftime("%B %d, %Y") %></p>
                        </div>
                        <div class="form-inline">
                            <div class="form-group">
                                <p><%= review.rating %>.00/5.00</p>
                            </div>
                            <div class="form-group">
                                <div class="star-rating" data-score= <%= review.rating %> ></div>
                            </div>
                        </div>
                    </div>
                <% end %> <!-- close reviews -->
            <% else %>
                <div class="col-xs-12">
                    <p><i><%= "#{@profile.user.first_name} does not have any reviews" %></i></p>
                </div>
            <% end %>
        </div> <!-- close row -->
        
    </div> <!-- close right side of page-->


    <div class="col-xs-12 col-sm-4 col-md-3 col-md-offset-1"> <!-- left side of page -->
        <div class="center">
            <%= link_to "Hire Me Now", new_profile_order_path(@profile), class: "button", data: { no_turbolink: true } %>
            <h5>or</h5>
            <%= link_to "Send me a message", new_message_path(:user => @user) %>
        </div><br>
        <hr style="height:4px;border:none;color:#555;background-color:#555;" />
        <h3><%= number_to_currency(@profile.price) %>/hour</h3>
        <hr style="height:1px;border:none;color:#555;background-color:#555;" />
        <h5>
            <% if @reviews.present? %>
                <div class="form-inline">
                    <div class="form-group">
                        <h5><%= "#{@average_rating}/5.00" %></h5>
                    </div>
                    <div class="form-group">
                        <div class="star-rating" data-score= <%= @average_rating %> ></div>
                    </div>
                </div>
            <% else %>
                <p><i>No Average Rating</i></p>
            <% end %>
            
        </h5>
        <hr style="height:1px;border:none;color:#555;background-color:#555;" />
        <h5><%= "#{@reviews.length} Reviews" %></h5>
        <hr style="height:1px;border:none;color:#555;background-color:#555;" />
        <% if @profile.user.provider == "linkedin" %>
            <h5><%= @profile.user.location %></h5>
        <% else %>
            <h5><%= @profile.location %></h5>
        <% end %>
        
        <hr style="height:1px;border:none;color:#555;background-color:#555;" />
    </div> <!-- close left side  -->

</div> <!-- close main row -->

<script>
  $('.star-rating').raty({
    path: 'https://s3.amazonaws.com/yelp-demo-2014/Stars/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/profiles/sleeping_beauty.html.erb
<%= @profile.price %>