config/routes.rb
Rails.application.routes.draw do
  
  devise_for :customers
  
  get "tags/:tag" => "profiles#index", as: :tag

  post '/rate' => 'rater#create', :as => 'rate'
  get "/messages" => redirect("/conversations")
  resources :messages do
  member do
    post :new
  end
end
resources :conversations do
  member do
    post :reply
    post :trash
    post :untrash
  end
 collection do
    get :trashbin
    post :empty_trash
 end
end

  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations", :omniauth_callbacks => "callbacks" }
  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end

  get "additional_fields/:id" => "users#additional_fields", as: :additional_fields

  resources :profiles do
    collection do
      get 'search'
    end
    resources :orders 
    resources :reviews
  end

  post '/complete_purchase/:id' => "orders#complete_purchase", as: :complete_purchase
  get 'cindarella/:id' => "orders#cindarella"
  
  get "sales" => "orders#sales"
  get "purchases" => "orders#purchases"

  get 'complete_profile' => "profiles#complete_profile" #show of /profiles/:id
  get 'bank_account/:id' => "profiles#bank_account", as: :bank_account
  post 'update_bank_account/:id' => "profiles#update_bank_account", as: :update_bank_account
  
  get 'pages/about'
  get 'pages/contact'
  get 'home' => "pages/home"
  get 'pages/type'

  root 'pages#home'

end

app/models/order.rb
class Order < ActiveRecord::Base

	validates :address, :city, :state, :zip_code, presence: true

	belongs_to :profile
	belongs_to :customer
	belongs_to :seller, class_name: "User"
	
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:new, :create, :purchases]
  before_action :authenticate_customer!, only: [:new, :create, :purchases]

  

  # Transfer Funds to Seller/Put method
  def complete_purchase

    if current_user.stripe_account.present?
      @order = Order.find(params[:id])

      Stripe.api_key = ENV["STRIPE_SECRET_KEY"]
      token = params[:stripeToken]

      Stripe::Transfer.create(
        :amount => (@order.amount * 0.8572).floor,
        :currency => "usd",
        :destination => current_user.stripe_account,
        :description => "Payment from #{@order.customer.first_name}",
        :source_transaction => @order.charge_id
      )
      redirect_to root_path
    else
      flash[:alert] = "Please add your bank account information."
      redirect_to bank_account_path(current_user.profile.id)
    end

  end

  def cindarella
    @cid = params[:id]
    @kim = params[:home_number]
  end

  def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end

  def purchases
    @orders = Order.all.where(customer: current_customer).order("created_at DESC")
  end  

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @profile = Profile.find(params[:profile_id])
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @profile = Profile.find(params[:profile_id])
    @seller = @profile.user

    @order.profile_id = @profile.id
    @order.customer_id = current_customer.id
    @order.seller_id = @seller.id

    Stripe.api_key = ENV["STRIPE_SECRET_KEY"]
    token = params[:stripeToken]

    begin
      charge = Stripe::Charge.create(
        :amount => (@profile.price * 105).floor,
        :currency => "usd",
        :card => token,
        )
      flash[:notice] = "Thanks for ordering!"
    rescue Stripe::CardError => e
      flash[:danger] = e.message
    end

    @order.charge_id = charge.id
    @order.amount = charge.amount
    current_customer.save

    respond_to do |format|
      if @order.save
        format.html { redirect_to new_message_path(:user => @seller) }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :state, :zip_code)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for([@profile, @order]) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="stripe_error" class="alert alert-danger" style="display:none">
    <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :city %>
        <%= f.text_field :city, class: "form-control" %>
      </div>
    </div>
    <div class="col-xs-6 col-sm-3">
      <div class="form-group">
        <%= f.label :state %>
        <%= f.text_field :state, class: "form-control" %>
      </div>
    </div>
    <div class="col-xs-6 col-sm-3">
      <div class="form-group">
        <%= f.label :zip_code %>
        <%= f.text_field :zip_code, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-xs-8 col-sm-6">
        <%= label_tag :card_number, "Credit Card Number" %>
        <%= text_field_tag :card_number, nil, { :name => nil, :'data-stripe' => "number", class: "form-control" } %>
      </div>
      <div class="col-xs-4 col-sm-2">
        <%= label_tag :card_code, "CVC" %>
        <%= text_field_tag :card_code, nil, { :name => nil, :'data-stripe' => "cvc", class: "form-control" } %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag nil, "Expiration Date" %>
    <div class="row">
      <div class="col-xs-6 col-sm-3 col-md-2">
        <div class="form-group">
          <%= select_month nil, { use_two_digit_numbers: true }, { :name => nil, :'data-stripe' => "exp-month", class: "form-control" } %>
        </div>
      </div>
      <div class="col-xs-6 col-sm-3 col-md-2">
        <div class="form-group">
          <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year+10 }, { :name => nil, :'data-stripe' => "exp-year", class: "form-control" } %>
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit class: "button button-small" %>
  </div>
<% end %>

app/views/orders/cindarella.html.erb
<h1>Hello World</h1>

<%= @cid %>

<%= @kim %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.address %></td>
        <td><%= order.city %></td>
        <td><%= order.state %></td>
        <td><%= order.zip_code %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>
<div class="row">
	<div class="col-md-4">
		
	</div>
	<div class="col-md-8">
		<div class="panel panel-default">
		  <div class="panel-body">
		    <%= render 'form' %>
				<%= link_to 'Back', profile_orders_path %>
		  </div>
		</div>
		
	</div>
</div>

app/views/orders/purchases.html.erb
<div class="center">
  <h2>Your Purchase History</h2>
</div><br>


<table class="table table-hover">
  <thead>
    <tr>
      <th class="center">Designer Name</th>
      <th class="center">Price</th>
      <th class="center">Order Date</th>
      <th class="center">Order Number</th>
    </tr>
  </thead>

  <% @orders.each do |order| %>
    <tbody>
      <tr>
        <td class="center"><%= "#{order.seller.first_name} #{order.seller.last_name}" %></td>
        <td class="center"><%= number_to_currency(order.profile.price) %></td>
        <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
        <td class="center"><%= order.id %></td>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/orders/sales.html.erb
<div class="center">
  <h2>Your Sales History</h2>
</div><br>


<table class="table table-hover">
  <thead>
    <tr>
      <th class="center">Buyer Name</th>
      <th class="center">Price</th>
      <th class="center">Order Date</th>
      <th class="center">Order Number</th>
      <th class="center">Action</th>
    </tr>
  </thead>

  <% @orders.each do |order| %>
    <tbody>
      <tr>
        <td class="center"><%= "#{order.buyer.first_name} #{order.buyer.last_name}" %></td>
        <td class="center"><%= number_to_currency(order.profile.price) %></td>
        <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
        <td class="center"><%= order.id %></td>
        <td class="center"><%= button_to "Mark as completed", complete_purchase_path(order.id), class: "button button-xs" %></td>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @order.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @order.state %>
</p>

<p>
  <strong>Zipe code:</strong>
  <%= @order.zipe_code %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>