config/routes.rb
Rails.application.routes.draw do
  
  devise_for :customers
  
  get "tags/:tag" => "profiles#index", as: :tag

  post '/rate' => 'rater#create', :as => 'rate'
  get "/messages" => redirect("/conversations")
  resources :messages do
  member do
    post :new
  end
end
resources :conversations do
  member do
    post :reply
    post :trash
    post :untrash
  end
 collection do
    get :trashbin
    post :empty_trash
 end
end

  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations", :omniauth_callbacks => "callbacks" }
  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end

  get "additional_fields/:id" => "users#additional_fields", as: :additional_fields

  resources :profiles do
    collection do
      get 'search'
    end
    resources :orders 
    resources :reviews
  end

  post '/complete_purchase/:id' => "orders#complete_purchase", as: :complete_purchase
  get 'cindarella/:id' => "orders#cindarella"
  
  get "sales" => "orders#sales"
  get "purchases" => "orders#purchases"

  get 'complete_profile' => "profiles#complete_profile" #show of /profiles/:id
  get 'bank_account/:id' => "profiles#bank_account", as: :bank_account
  post 'update_bank_account/:id' => "profiles#update_bank_account", as: :update_bank_account
  
  get 'pages/about'
  get 'pages/contact'
  get 'home' => "pages/home"
  get 'pages/type'

  root 'pages#home'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_profile
  before_action :authenticate_user!

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @profile = Profile.find(params[:profile_id])
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.profile_id = @profile.id
    @review.user_id = current_user.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to profile_path(@profile), notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_profile
      @profile = Profile.find(params[:profile_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :title, :comment)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for([@profile, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.label :rating %>
  <div id="star-rating"></div>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %><br>
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :comment %><br>
        <%= f.text_area :comment, class: "form-control" %>
      </div>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.submit class: "button button-small" %>
  </div>
<% end %>

<script>
  $('#star-rating').raty({
    path: 'https://s3.amazonaws.com/yelp-demo-2014/Stars/',
    scoreName: 'review[rating]',
  });
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Title</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.title %></td>
        <td><%= review.comment %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/reviews/new.html.erb
<h2>Write a review about your experience</h2>

<%= render 'form' %>

<%= link_to 'Back', profile_reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>