config/routes.rb
Rails.application.routes.draw do
  
  devise_for :customers
  
  get "tags/:tag" => "profiles#index", as: :tag

  post '/rate' => 'rater#create', :as => 'rate'
  get "/messages" => redirect("/conversations")
  resources :messages do
  member do
    post :new
  end
end
resources :conversations do
  member do
    post :reply
    post :trash
    post :untrash
  end
 collection do
    get :trashbin
    post :empty_trash
 end
end

  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations", :omniauth_callbacks => "callbacks" }
  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end

  get "additional_fields/:id" => "users#additional_fields", as: :additional_fields

  resources :profiles do
    collection do
      get 'search'
    end
    resources :orders 
    resources :reviews
  end

  post '/complete_purchase/:id' => "orders#complete_purchase", as: :complete_purchase
  get 'cindarella/:id' => "orders#cindarella"
  
  get "sales" => "orders#sales"
  get "purchases" => "orders#purchases"

  get 'complete_profile' => "profiles#complete_profile" #show of /profiles/:id
  get 'bank_account/:id' => "profiles#bank_account", as: :bank_account
  post 'update_bank_account/:id' => "profiles#update_bank_account", as: :update_bank_account
  
  get 'pages/about'
  get 'pages/contact'
  get 'home' => "pages/home"
  get 'pages/type'

  root 'pages#home'

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
  has_many :purchases, class_name: "Order", foreign_key: "customer_id"
end

app/models/order.rb
class Order < ActiveRecord::Base

	validates :address, :city, :state, :zip_code, presence: true

	belongs_to :profile
	belongs_to :customer
	belongs_to :seller, class_name: "User"
	
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/profile.rb
class Profile < ActiveRecord::Base



	belongs_to :user
	has_many :orders
	has_many :reviews, dependent: :destroy
  
	acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :industries, :companies


	validates :years_of_experience, :experience_level, :portfolio_link, :tag_list, :industry_list, :company_list, presence: true
	validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
	validates :company, :location, :summary, :image, :title, :linked_link, presence: true, unless: :email_signup?


	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "16x16>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def email_signup?
  	self.user.provider == "linkedin"
  end

  def search_data
  	{
  		title: title,
  		company: company,
  		user_title: user.headline,
  		industry: user.industry,
  		tag_name: tags.map(&:name),
  		first_name: user.first_name,
  		last_name: user.last_name,
  		location: user.location,
  		location1: location,
  	}
  end

  def self.facets_search(params)
    query = params[:query].presence || "*"
    conditions = {}
    conditions[:first_name] = params[:first_name] if params[:first_name].present?

    profiles = Profile.search query, where: conditions, 
      facets: [:first_name], 
      smart_facets: true, page: params[:page], suggest: true, highlight: true,
      per_page: 10
    profiles
  end

  

end

app/models/profile_skill.rb
class ProfileSkill < ActiveRecord::Base
  belongs_to :profile
  belongs_to :skill
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ActiveRecord::Base

	belongs_to :profile

	
end

app/models/skill.rb
class Skill < ActiveRecord::Base

	has_many :profile_skills
  has_many :profiles, through: :profile_skills

end

app/models/user.rb
class User < ActiveRecord::Base
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:linkedin]

  has_one :profile, dependent: :destroy
  has_many :sales, class_name: "Order", foreign_key: "seller_id"
  has_many :reviews, dependent: :destroy

  after_create :send_notification

  def send_notification
    MyMailer.new_user(self).deliver_now
  end

  validates :first_name, :last_name,  presence: true
  validates :email, uniqueness: true

  acts_as_messageable

  def mailboxer_email(object)
    #Check if an email should be sent for that object
      #if true
        return email
      #if false
        #return nil
    end

  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.headline = auth.info.headline
        user.first_name = auth.info.first_name
        user.last_name = auth.info.last_name
        user.industry = auth.info.industry
        user.location = auth.info.location
        user.summary = auth.extra.raw_info.summary
        user.connections = auth.extra.raw_info.numConnections
        user.linkedin_photo_url = auth.info.image
        user.linkedin_url = auth.info.urls.public_profile
        user.linkedin_position = auth.extra.raw_info.positions.values[1]
      end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end

  def about
  	@foot = params[:multiple].to_i * 2
  end

  def contact
  	@cuntact = params[:funky]
  end

  def type
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def active_page(active_page)
    @active == active_page ? "active" : ""
  end
  
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div><br>
    HTML

    html.html_safe
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_alert_message.html.erb
	<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) && !@disable_nav %>
      <div class="alert alert-<%= name.to_s == "notice" ? "success" : "danger" %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><center>
        <%= content_tag :div, msg, :id => "flash_#{name}" %></center>
      </div>
    <% end %>
  <% end %>

app/views/layouts/_bootstrap.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse normal" role="banner">
  		<div class="container">
    		<div class="navbar-header">
		      	<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
		      	</button>
      			<a href="/" class="navbar-brand">OneHourUX</a>
    		</div>
    		<nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      			<ul class="nav navbar-nav navbar-left">
              <li>
                <%= form_tag search_profiles_path, method: 'get', class: "navbar-form" do %>
                  <%= text_field_tag :search, params[:search], class: "form-control" %>
                  <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
                <% end %>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.first_name %> <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <% unless current_user.profile.blank? %>
                        <li><%= link_to "View Profile", profile_path(current_user.profile) %></li>
                        <li><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></li>
                      <% end %>
                      <li><%= link_to "Account Settings", edit_user_registration_path %></li>
                      <li><%= link_to "Sales History", sales_path %></li>
                    </ul>
                </li>
                <li class="dropdown">
                  <%= link_to 'Inbox', conversations_path %>
                </li>
                <li class="dropdown">
                  <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
                </li>
              <% elsif customer_signed_in? %>
                <li class="dropdown">
                  <%= link_to "Edit Profile", edit_customer_registration_path %>
                </li>
                <li class="dropdown">
                  <%= link_to "Sign Out", destroy_customer_session_path, method: :delete %>
                </li>
              <% else %>
                <li class="dropdown">
                  <%= link_to "Log In", new_customer_session_path %>
                </li>
                <li class="dropdown">
                  <%= link_to "Sign Up", new_customer_registration_path %>
                </li>
                <li class="dropdown">
                  <%= link_to "UXD Log In", new_user_session_path %>
                </li>
                <li class="dropdown">
                  <%= link_to "UXD Sign Up", new_user_registration_path %>
                </li>
              <% end %>          
      				<!-- <li class="dropdown">
        				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
          					Home alts <b class="caret"></b>
          				</a>
          				<ul class="dropdown-menu">
							<li><a href="index.html">Home 1 (Static)</a></li>
							<li><a href="index3.html">Home 2 (Sidebar menu)</a></li>
							<li><a href="index4.html">Home 3 (Slider)</a></li>
				        </ul>
        			</li>
      				<li class="dropdown">
        				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
          					Showcase <b class="caret"></b>
          				</a>
          				<ul class="dropdown-menu">
							<li><a href="features.html">Features</a></li>
							<li><a href="services.html">Services</a></li>
				        </ul>
        			</li>
        			<li class="dropdown">
          				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
          					Pricing <b class="caret"></b>
          				</a>
          				<ul class="dropdown-menu">
							<li><a href="pricing.html">Pricing charts</a></li>
							<li><a href="charts.html">Comparison tables</a></li>
				        </ul>
        			</li>
        			<li class="active dropdown">
        				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
          					More pages <b class="caret"></b>
          				</a>
          				<ul class="dropdown-menu">
							<li><a href="aboutus.html">About us</a></li>
							<li><a href="contactus.html">Contact us</a></li>
							<li><a href="gallery.html">Gallery</a></li>
							<li><a href="portfolio.html">Portfolio</a></li>
							<li><a href="portfolio-item.html">Portfolio Item</a></li>
							<li><a href="invoice.html">Invoice page</a></li>
							<li><a href="timeline.html">Timeline Page</a></li>
							<li><a href="docs.html">API Documentation</a></li>
							<li><a href="support.html">Support</a></li>
							<li><a href="coming-soon.html">Coming Soon</a></li>
							<li><a href="status.html">Status</a></li>
							<li><a href="signup.html">Sign Up & Sign In</a></li>
							<li><a href="signup-rotate.html">Sign Up Miscellaneous</a></li>
							<li><a href="404.html">404 Page</a></li>
				        </ul>
        			</li>
        			<li class="dropdown">
        				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
	      					Blog <b class="caret"></b>
	      				</a>
	      				<ul class="dropdown-menu">
							<li><a href="blog.html">Blog </a></li>
							<li><a href="blogpost.html">Blog post</a></li>
				        </ul>
        			</li>
      			</ul>
      			<ul class="nav navbar-nav navbar-right visible-md visible-lg">
      				<li>
          				<a href="signup.html" class="button">Sign up free</a>
        			</li>
      			</ul> -->
    		</nav>
  		</div>
	</header>

app/views/layouts/_home_header.html.erb
  <header class="navbar navbar-inverse hero" role="banner">
        <div class="container">
          <div class="navbar-header">
              <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a href="/" class="navbar-brand">OneHourUX</a>
          </div>
          <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
              <ul class="nav navbar-nav navbar-right">  
                <% if customer_signed_in? %>
                  <li class="dropdown">
                    <%= link_to "Sign Out", destroy_customer_session_path, method: :delete %>
                  </li>
                <% else %>
                  <% if user_signed_in? %>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.first_name %> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                          <% if current_user.profile.nil? %>
                            <li><%= link_to "Create Profile", new_profile_path %></li>                         
                          <% else %>
                            <li><%= link_to "Account Settings", edit_user_registration_path %></li>
                            <li><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></li>
                            <li><%= link_to "View Profile", profile_path(current_user.profile) %></li>
                          <% end %>
                        </ul>
                    </li>
                    <li class="dropdown">
                      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
                    </li>
                  <% else %>
                    <li class="dropdown">
                      <%= link_to "Log In", new_customer_session_path %>
                    </li>
                    <li class="dropdown">
                      <%= link_to "Sign Up", new_customer_registration_path %>
                    </li>
                    <li class="dropdown">
                      <%= link_to "UXD Log In", new_user_session_path %>
                    </li>
                    <li class="dropdown">
                      <%= link_to "UXD Sign Up", new_user_registration_path %>
                    </li>
                  <% end %>          
                <% end %>
                  
                  
                  <!-- <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Showcase <b class="caret"></b></a>
                      <ul class="dropdown-menu">
                        <li><a href="features.html">Features</a></li>
                        <li><a href="services.html">Services</a></li>
                      </ul>
                  </li> -->
                  <!-- <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Pricing <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                  <li><a href="pricing.html">Pricing charts</a></li>
                  <li><a href="charts.html">Comparison tables</a></li>
                    </ul>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        More pages <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                  <li><a href="aboutus.html">About us</a></li>
                  <li><a href="contactus.html">Contact us</a></li>
                  <li><a href="gallery.html">Gallery</a></li>
                  <li><a href="portfolio.html">Portfolio</a></li>
                  <li><a href="portfolio-item.html">Portfolio Item</a></li>
                  <li><a href="invoice.html">Invoice page</a></li>
                  <li><a href="timeline.html">Timeline Page</a></li>
                  <li><a href="docs.html">API Documentation</a></li>
                  <li><a href="support.html">Support</a></li>
                  <li><a href="coming-soon.html">Coming Soon</a></li>
                  <li><a href="status.html">Status</a></li>
                  <li><a href="signup.html">Sign Up & Sign In</a></li>
                  <li><a href="signup-rotate.html">Sign Up Miscellaneous</a></li>
                  <li><a href="404.html">404 Page</a></li>
                    </ul>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Blog <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                  <li><a href="blog.html">Blog</a></li>
                  <li><a href="blogpost.html">Blog Post</a></li>
                    </ul>
                  </li>  -->
              </ul>
          </nav>
        </div>
    </header>

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" /> 
  <title>OneHourUX</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= render 'layouts/bootstrap' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://js.stripe.com/v2/' %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => 'stripe-key', :content => ENV["STRIPE_PUBLIC_KEY"] %>
</head>
<body>
  
  <%= render 'layouts/alert_message' %>
  
  <% if current_page?(root_path) %>
    <%= render 'layouts/home_header' %>
    <%= yield %>
  <% elsif current_page?(new_profile_path) %>
    <%= render 'profiles/new_profile_header' %>
    <div class="container">
      <%= yield %>
    </div>
  <% else %>
    <%= render 'layouts/header' unless @disable_nav %>
    <div class="container">
      <%= yield %>
    </div>
  <% end %>

	<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/about.html.erb
<div id="second-option">
    <div class="container">
      <div class="row center">
        <h2 class="global-h2">How it works</h2>
      </div>
      <div class="row center">
        <div class="col-md-4 feature">
          <%= image_tag "icons/circle-icons/one-color/dev.png" %>
          <h4 class="global-h4">Find</h4>
          <p>With some customization you can make this product apply to your branding guidelines and amaze your customers at the same time.</p>
        </div>
        <div class="col-md-4 feature">
          <%= image_tag "icons/circle-icons/one-color/dev.png" %>
          <h4 class="global-h4">Hire</h4>
          <p>With some customization you can make this product apply to your branding guidelines and amaze your customers at the same time.</p>
        </div>
        <div class="col-md-4 feature">
          <%= image_tag "icons/circle-icons/one-color/dev.png" %>
          <h4 class="global-h4">Meet</h4>
          <p>We don't impose any design restrictions, you are free to customize it as you see fit and it's easy to use.</p>
        </div>
      </div>
    </div>
  </div>
  </div>

  <div class="row">
  	<div class="col-md-4">
  		<div class="center">
  			<h1>Hello World Here Comes Another Awesome </h1>
  			<p>Hello World</p>
  			<p>We don't impose any design restrictions, you are free to customize it as you see fit and it's easy to use.</p>
  		</div>
  	</div>
  </div>

app/views/pages/contact.html.erb
<label for="">Name</label>
<form class="form-inline">
	
  <div class="form-group">
    <input type="text" class="form-control" id="exampleInputName2" placeholder="Jane Doe">
  </div>
  <div class="form-group">
  	<p> TO </p>
  </div>
	
  <div class="form-group">
    <input type="email" class="form-control" id="exampleInputEmail2" placeholder="jane.doe@example.com">
  </div>

</form>

app/views/pages/type.html.erb
<div class="row">
	<div class="center">
		<div class="form-group">
			<h2>Let's get started<br>First, tell us what you're looking for.</h2>
		</div>
	</div>
</div> <!-- close row -->
<div id="selector"
	<div class="row">
		<div class="col-md-5">
			<div class="center">
				<div class="form-group">
					<h3>I want to hire a UX Designer</h3>
				</div>
				<div class="form-group">
					<h5>Find, collaborate with,<br>and pay an expert</h5>
				</div>
				<div class="line-spacer">
					<%= link_to "Hire", new_user_registration_path, class: "button" %>
				</div>
			</div>
		</div>
		<div class="col-md-2">
			<div class="row">
				<div class="center">
					<div class="verticalLine"></div>
				</div>
			</div>
		</div>
		<div class="col-md-5">
			<div class="center">
				<h3>I want to join as a UX Designer</h3>
				<h5>Find freelance projects<br>and earn extra money.</h5>
				<%= link_to "Sign up with LinkedIn", user_omniauth_authorize_path(:linkedin), class: "button" %>
			</div>
		</div> <!-- close md-5 -->

	</div> <!-- close row -->
</div?